const meditacionesFrases = [
    "¡Cuán pequeña parte del tiempo, infinito e insondable, se ha distribuido a cada uno, puesto que en un momento va a abismarse en la nada! ¡Cuán pequeña porción de la substancia universal! ¡Cuán pequeña parte de la vida universal! ¡Cuán pequeña gleba de toda la tierra es ésta en que te arrastras! Considerando todo esto, nada estimes por cosa grande, sino el obrar conforme a las normas de tu naturaleza y el sentir según las exigencias de la naturaleza común.",
    "¡Qué perverso y fingido es el que dice Yo he decidido conducirme limpiamente contigo! ¿Qué haces, pobre amigo mío? No es necesario andarse por las ramas. Esto se verá por sí mismo; debe leerse en tu rostro; inmediatamente suena esto en tu voz; al punto se manifiesta en tus ojos, así como la persona amada conoce todo al instante en las miradas de sus amantes. En suma, el hombre recto y virtuoso debe ser tal cual es el que huele a sobaquina, de manera que quien se le acercare sienta, quiera el otro o no quiera, desde el primer momento, lo que es en realidad. Pues la afectación es arma de doble filo. Nada hay más odioso que la amistad de lobo. Evita este vicio más que los demás. El hombre de veras bueno, recto, benévolo, manifiesta estas cualidades en sus ojos, sin poder ocultarlas.",
    "En los escritos de los efesios se hallaba este aviso: «Tened siempre presente el ejemplo de aquellos antiguos que se dedicaron al ejercicio de la virtud».",
    "Todos aquellos bienes a que deseas llegar por rodeos, puedes alcanzarlos en seguida, si no te quieres mal a ti mismo. Esto es: si dejando de lado todo lo pasado, confías lo futuro a la providencia, y enderezas lo presente según la piedad y la justicia: según la piedad, a fin de abrazar férvidamente cuanto te fuere dispensado, puesto que la naturaleza te lo destinó, y te destinó a ti para ello; según la justicia, para que libremente y sin trabas digas la verdad y obres conforme a la ley y al mérito del objeto. No te sirvan de obstáculo ni la maldad ni la opinión o la palabra ajenas, ni menos las sensaciones de esta mísera carne que te rodea: allá se las tendrá la parte afectada. Ahora, pues, si un día u otro estás al fin de la carrera, te despides de todo lo restante y respetas sólo tu recta razón y la parte divina que hay en ti; si temes, no el poner fin a la vida, sino el no haber comenzado nunca a vivir conforme a la naturaleza, serás un hombre digno de ese mundo que te engendró, dejarás de ser huésped en tu misma patria; de maravillarte de lo que sucede todos los días como si fuera cosa inesperada, de no estar pendiente de tal y tal cosa.",
    "Muchas veces me pregunto, maravillado, cómo es que amándose cada uno a sí mismo más que a todos los otros, estime en menos la opinión propia formada de sí, que la opinión ajena que se merece. Puesto que si un dios apareciéndose a uno de nosotros, o si un sabio maestro ordenase a uno de nosotros no imaginar, no pensar nada, sin proferirlo al mismo punto en voz alta, no habría quien pudiera soportarlo un solo día. En esta conformidad, respetamos más al prójimo cuando opina algo acerca de nosotros que a nosotros mismos.",
    "Cuán ridículo y extraño es aquel que se maravilla de cosa alguna de cuantas pasanen esta vida!",
    "O domina una fatalidad de destino y un orden inviolable, o una providencia aplacable, o un caos entregado al azar, sin dirección alguna. Ahora bien: si reina una fatalidad inflexible, ¿a qué intentas resistirla? Si reina una providencia capaz de dejarse aplacar, hazte digno del socorro divino. Si reina un caos sin ninguna dirección, conténtate de poseer en ti mismo, en medio de ese torbellino, una inteligencia capaz de guiarte. Y si el torbellino te arrollare, que se lleve tras sí tu cuerpo, tu aliento y todas las otras cosas externas: no te arrebatará la inteligencia.",
    "En primer lugar, procura no hacer cosa alguna irreflexivamente, sin relacionarlo con algo; en segundo lugar, no dirijas las acciones a otra cosa más que a la utilidad del bien común.",
    "A los que te preguntaren: «¿En dónde viste a los dioses, y cómo compruebas su existencia, para darles ese culto?», respóndeles, ante todo, que son visibles a nuestros ojos; además, aunque yo no haya visto mi alma, con todo también la respeto. Y lo mismo acontece con los dioses: por las mismas razones que experimento los efectos de su poder en todas las coyunturas, comprendo que existen y los venero.",
    "No es fácil tropezar con un hombre que sea desgraciado por dejar de entrometerse en lo que ocurre en el alma de los demás. Pero los que no escudriñan los movimientos de su propia alma, fuerza es que sean desgraciados.",
    "Como filósofo ha juzgado Teofrasto, cuando en aquella comparación que hacía de las faltas entre sí, afirma —como haría cualquiera que comparase, regido por el sentido común— que las faltas cometidas por concupiscencia son más graves que las cometidas por ira. En efecto, el hombre montado en cólera experimenta cierta pena y 11 una secreta angustia de corazón, al desviarse de la razón. Pero el que peca por concupiscencia, vencido por el deleite, aparenta una cierta debilidad y afeminamiento al incurrir en estas faltas. Con razón, pues, y como filósofo digno de tal nombre, Teofrasto sostiene que los desórdenes cometidos por placer son más censurables que los cometidos con dolor. Ciertamente, en el último caso, el culpable parece ser un hombre provocado por la justicia y forzado a inflamarse en cólera; en el primer caso, por el contrario, es él mismo quien ha decidido ser injusto, arrastrado a obrar así por el capricho de la concupiscencia.",
    "Conforma siempre tus acciones, palabras y pensamientos a la idea de que puedes salir a cada instante de la vida; por más que, si hay dioses, despedirse de los hombres nada quiere decir, pues éstos no sabrían hundirte en la desgracia. Y si no los hay, o bien si no se cuidan de las cosas humanas, ¿a qué vivir en un mundo vacío de dioses o falto de providencia?",
    "Acuérdate de que la facultad rectora se hace inexpugnable cuando, recogida dentro de sí, se contenta con no hacer lo que no es su gusto, aunque sólo se oponga por capricho. ¿Qué será, pues, cuando, gobernada por la razón, emita prudentemente un juicio? La inteligencia libre de pasiones es como una ciudadela; y realmente el hombre no tiene posición más segura donde retirarse para no ser en adelante capturado. Quien no la ha visto es un ignorante; quien, habiéndola visto, no se ampara en ella es un desdichado.",
    "Nada más infeliz que el hombre que lo inquiere todo girando de aquí para allá, que escruta, como dice el poeta, «las profundidades de la tierra», que indaga por conjeturas lo que acontece en el alma ajena, sin acabar de entender que le bastaría sólo aplicarse al dios que habita en su interior y venerarle como es debido. Este culto consiste en conservarse puro de pasiones; de temeridad y de disgusto por aquello que procede de los dioses y de los hombres. Porque lo que viene de los dioses es digno de respeto, por ser obra de sí virtuosa; y lo que viene de los hombres nos es caro a causa del parentesco, si bien a veces no deja de ser, en cierto sentido, objeto de compasión, por su ignorancia del bien y del mal, ceguera no menor que la que nos impide poder discernir lo blanco de lo negro.",
    "Se deshonra el alma del hombre particularmente cuando, por lo que a sí toca, viene a hacerse como un divieso o una excrecencia en el cuerpo del mundo; porque irritarse con alguno de los acontecimientos que sobrevienen es como un absceso de la naturaleza universal, de la cual participan las naturalezas de todos los otros seres. El alma se deshonra asimismo cuando se muestra adversa a alguno de los otros hombres, o se comporta con él con intención de hacerle mal, como acontece con las almas poseídas de ira. Lo tercero, se deshonra cuando se da por vencida del dolor o el placer. Lo cuarto, cuando disimula, finge y altera la verdad por obra o de palabra. Lo quinto, cuando lanza su actividad o sus apetitos sin blanco fijo, y lo ejecuta todo al azar, y sin continuidad, siendo así que aun las más pequeñas acciones debieran tender a un fin propuesto: y el fin de los seres racionales es obedecer a la razón y a la ley de la naturaleza, la más augusta de las ciudades y gobiernos.",
    "Hipócrates, después de curar muchas enfermedades, al cabo cayó enfermo él mismo y murió. A muchos habían predicho los caldeos la muerte, y no por esto dejó de llegarles también su día y destino. Alejandro, Pompeyo y Cayo César, después de haber tantas veces destruido hasta los cimientos ciudades enteras y haber triturado en campo de batalla millaradas de elefantes y jinetes, también ellos, al fin, perdieron la vida. Heráclito, luego de tan prolijos estudios sobre el último incendio del mundo, enfermo de hidropesía y recubierta de inmundicias la piel, murió. Murió Demócrito comido de piojos; y piojos, bien que de otra casta, quitaron la vida a Sócrates. ¿A qué todo esto? Te embarcaste, hiciste el viaje, llegaste al puerto: ¡desembarca! Si es para entrar en una nueva existencia, no echarás de menos a los dioses. No es para quedar del todo insensible, cesarás en los dolores y los placeres, librándote de servir a un envoltorio corporal tanto más vil cuanto le sobrepasa la parte esclavizada: ésta, es inteligencia y divinidad; aquél, fango y sangre impura.",
    "No malogres la parte de vida que te queda en averiguar vidas ajenas, a no ser que te propongas algún fin útil a la comunidad. Te privas ciertamente de cumplir tu deber al revolver en tu imaginación lo que hace fulano y por qué lo hace, qué dice, qué piensa, qué trama, y otras ocupaciones de esta índole que te distraen de la consideración de tu facultad rectora. Conviene, pues, no ensartar en la cadena de nuestros pensamientos lo que es temerario y vano y, más especialmente, lo fútil y lo malvado. Hay que avezarse, además, a tener sólo ideas tales que si alguien de repente te preguntare, bruscamente: «¿En qué piensas ahora?», pudieras responder al instante, con toda franqueza: «en esto» o «en aquello». Se dejará ver entonces, pronto y evidentemente, que todo lo tuyo es simple, bondadoso, digno de un ser sociable e indiferente a los placeres y, en su conjunto, a las ideas de una vida voluptuosa; un ser que no abriga envidia, celos, desconfianza u otra pasión por la cual te fuera preciso avergonzarte al manifestar que la posee tu ánimo",
    "No vagabundees más. Que no has de tener tiempo para releer tus notas, ni las antiguas historias de los romanos y los griegos, ni extractos de tratados que habías reservado para tu vejez. Apresúrate, pues, en llegar al fin; despídete de las vanas esperanzas y mira por tu bien, si tienes cuenta contigo mismo, hasta que sea posible.",
    "Por la mañana, cuando sintieses pereza al levantarte, piensa: Yo me levanto para cumplir con los oficios propios de un hombre. ¿Me desazonaré, pues, si voy a ejecutar aquello para lo que nací, para lo que vine al mundo? ¿A esto fui formado, para arrellanarme en la cama, caliente entre mis cobertores? —Pero esto, dirás, es más agradable—. ¿Fuiste formado, entonces, para solazarte? Y, en suma, ¿naciste para la pasividad o para la actividad? ¿No ves cómo las plantas, los pájaros, las hormigas, las arañas, las abejas, tienen cada cual su tarea propia y contribuyen, a su vez, al buen orden del mundo? Entonces tú, ¿no querrás hacer lo que incumbe al hombre? ¿No te apresurarás en poner por obra lo que se conforma con tu naturaleza?",
    "El señorío interior del hombre, cuando va bien concertado con la naturaleza, adopta respecto a los acontecimientos una posición tal, que en todo momento puede modificarla fácilmente, a tenor de las circunstancias. No tiene preferencia por ninguna materia determinada; se dirige a los objetos principales, aunque con la debida reserva, y si alguno se le opone, conviértelo en materia propia de virtud, no de otra manera que el fuego cuando se apodera de los cuerpos que se le echan encima. Una pequeña mecha se apagaría, pero un fuego vehemente asimila pronto cuanto se le arroja, lo convierte en sí mismo y se levanta así más alto.",
    "Le buscan para solaz el campo, la playa, la montaña; cosas que tú mismo acostumbras a desear con el más vivo anhelo. Todo esto denota vulgaridad de espíritu, teniendo uno en su mano, a cualquier hora, el retirarse en sí mismo. En ningún lugar encuentra el hombre refugio más apacible, más tranquilo, que en su propia alma, sobre todo cuando atesora aquellos bienes que, con una sola ojeada, nos devuelven en seguida la libertad del espíritu: y lo que yo llamo libertad de espíritu no es otra cosa que el estado de un alma bien ordenada.",
    "La muerte, lo mismo que la generación, es un misterio de la naturaleza. La última es la condensación de los mismos elementos que en la otra se disuelven. En suma, nada hay allí que deba avergonzarnos, pues no se halla en ellas cosa que no sea conforme a la condición del ser intelectivo ni a la causa de su constitución.",
    "Haz por semejarte al peñasco batido sin cesar por las olas: permanece inmóvil y a su alrededor desmaya la efervescencia de las aguas. «¡Infeliz de mí, dice uno, porque tal cosa me aconteció!». No, al contrario: «Dichoso yo, porque habiéndome ocurrido esto, continúo sin pena alguna, ni quebrantado por lo presente ni amedrentado por lo venidero. Una semejante desgracia hubiera podido ocurrir a cualquier otro; y éste no hubiera sabido continuar, como yo, sin apenarse». ¿Y por qué será la adversidad un infortunio más bien que una ventura?",
    "Las cosas están recubiertas, a la verdad, de una tal veladura, que a no pocos filósofos, y no de los recién llegados, han parecido del todo incomprensibles; aun los mismos estoicos, las juzgan por lo menos difíciles de comprender. Y es que todo asenso nuestro está sujeto a errar. ¿Dónde hallarás uno que sea inmutable? Da un paso ya hacia los mismos objetos que caen bajo nuestro conocimiento: ¡cuán efímeros son, viles, capaces de pasar al dominio de un libertino, de una ramera, de un malhechor! Después de esto, pasa a las costumbres de aquellos con quienes vives: el más cortés de todos es difícilmente aguantable, por no decir que apenas puede él soportarse a sí mismo.",
    "Estoy compuesto de causa formal y materia. Ninguno de estos elementos será reducido a la nada, del mismo modo que tampoco han salido de la nada. Pues cada parte de mi ser tendrá asignado otro lugar, mediante la transformación en otra parte del mundo; y de nuevo ésta se transformará en otra parte del universo, y así continuará la sucesión hasta la eternidad. Por esta vía de transformación tuve yo principio, y lo mismo mis padres, y por su orden otros, hasta remontarnos así al infinito. Nada se opone a que esto parezca verdad, por más que se divida el gobierno del universo en períodos limitados.",
    "La mejor forma de vengarte de los que te injurian es que no les imites.",
    "Todos los objetos subsistentes se transformarán bien presto y se evaporarán, si es una la substancia universal; o bien se dispersarán",
    "La mayoría de los objetos, de que se admira el vulgo, se reducen a ciertos géneros universales, a aquellas substancias dotadas de una sola forma y de una naturaleza, cuales son las piedras, la madera, las higueras, los olivos. Los hombres de mediana esfera tienden a los seres que poseen alma sensitiva, como los rebaños de ganado mayor y menor. Los hombres de más honor se inclinan a los seres dotados de alma racional, pero no en cuanto es alma universal del mundo, sino de la que se aplica preferentemente a las artes o a alguna forma de ingenio; o, simplemente, gustan poseer un crecido número de esclavos. Mas el hombre que aprecia debidamente su alma racional, en cuanto es universal y social, dejado aparte cualquier otro cuidado, procura guardar, ante todo, en su alma aptitudes y movimientos conformes a la razón y al bien común; y trabaja para que su semejante consiga este fin.",
    "Es vergonzoso que cuando tu cuerpo no renuncia a esta vida, renuncie la primera tu alma.",
    "¿Has visto alguna vez una mano cercenada, un pie o una cabeza cortada y lanzada a cierta distancia del resto del cuerpo? Lo mismo hace consigo, según sus medios, el que no acepta lo que le acaeciere, y se separa a sí mismo del conjunto o ejecuta algo no conducente al interés común. Y tú, en cierto modo, te has excluido de la unión peculiar de la naturaleza, de la cual eres miembro por tu nacimiento: ahora te cercenaste tú mismo. Pero, tan admirablemente se dispuso eso, que puedes reunirte de nuevo al todo. El hombre es el único ser a quien Dios otorgó la facultad de incorporarse de nuevo con su todo, después de haberse separado y cercenado. Considera, por tanto, la bondad con que Dios ha honrado al hombre: ha puesto en su mano el que no se separase de todo punto del universo, y que, una vez segregado, pudiese restituirse de nuevo, fundiéndose con él y recuperando el lugar de miembro participante.",
    "Un obstáculo que dificulte la sensación es un mal para la naturaleza sensitiva; un obstáculo al apetito es asimismo un mal para la naturaleza sensitiva. Del mismo modo puede haber algún otro obstáculo y algún otro mal para la constitución vegetativa. Así pues, un estorbo a la inteligencia será un mal para la naturaleza intelectiva. Aplícate todo esto a ti mismo. ¿Te sobreviene un dolor, un placer? Añade esto a la sensibilidad. ¿Le sobrevino un embarazo al movimiento instintivo? Si te dejas llevar por este movimiento sin reserva, ya en esto mismo estaba el daño de tu naturaleza racional; pero si conservas tu inteligencia no serás aún lesionado ni obstaculizado. Ninguna otra cosa suele oponerse a lo que es propio de la inteligencia más que ella misma; pues a ella no le llegan ni el fuego, ni el hierro, ni el tirano, ni la calumnia, ni otra cosa. Cuando consigue ser como una esfera bien redondeada, continúa siéndolo."

];

const cincoAnillosFrases = [
    `Para las personas que quieran aprender mi ciencia militar, existen normas para el aprendizaje de este arte:
    1.Considerad lo que ees correcto y verdadero
    2.Practicad y cultivad la ciencia
    3.Familiarizaos con las artes
    4.Conoced los principios del oficio
    5.Entended el perjuicio y beneficio de cada cosa.
    7.Tomad conciencia de lo que no es obvio
    8.Sed cuidadosos incluso en los asuntos pequeños
    9.No hagaís nada que sea inútil.`,
    `Existe el contagio en todo. Incluso el sueño puede ser contagiado, lo mismo que el bostezo. Existe el contagio incluso de una época
    En la ciencia militar a gran escala, cuando los adversarios están excitados y con toda evidencia tienen prisa por actuar, os comportáis como si estuvierais somnolientos, dando la apariencia de estar completamente relajados y tranquilos. Haced esto, y los mismos adversarios se verán influidos por este estado de ánimo y perderán su entusiamo.`,
    "Para el médico, curar es una forma de vida.",
    "En cualquier arte y en cualquier ciencia no debe ignorarse el ritmo.",
    "Aunque sean torpes en ellas, los guerreros deben fortalecer personalmente sus propias artes marciales tanto como puedan sus propias circunstancias.",
    "No leas por leer, ni imites, sino que debes tener interés por descubrir tú mismo estas cosas, se debe reflexionar.",
    "Si no seguís un auténtico camino hasta el final, una pequeña maldad al principio se convierte en una gran perversión.",
    "Es esencial reforzar firmemente el ataque en el momento de cualquier pérdida de posición por parte de un adversario, para impedirle que se recupere.",
    "La observación y la percepción son dos cosas separadas; el ojo que observa es más fuerte, el ojo que percibe es más débil.",
    "La desintegración es algo que le sucede a todas las cosas. Cuando se desploma un caballo, una persona o un adversario, se desmoronan del ritmo del tiempo.",
    "Las artes marciales son la forma de vida del guerrero. Especialmente los oficiales deberían practicar estas artes, y los soldados deben también conocer esta forma de vida.",
    "Al distinguir las ventajas de las armas de los guerreros, descubrimos que, cualquiera que sea el arma, existe un momento y una situación en la que ésta es apropiada.",
    "Es imprescindible dominar los principios del arte de la guerra y aprender a permanecer como un espíritu inmutable incluso cuando estáis en el corazón de la batalla.",
    "Lo que es esencial es hacer repentinamente un movimiento totalmente inesperado para el adversario, aprovecharos de la ventaja del temor causado y alcanzar la victoria en ese mismo instante y lugar.",
    "La verdadera ciencia de las artes marciales significa practicarlas de tal forma que sean útiles en cualquier ocasión, y enseñarlas de tal forma que sean útiles en todos los caminos.",
    "Es absolutamente imposible escribir esta ciencia con la precisión con la que la entiendo en mi corazón. Sin embargo, aunque las palabras sean insuficientes, los principios deben ser evidentes por sí mismos.",
    "Pon estos principios en tu corazón para entrenarse en el camino de la estrategia. Si no miras las cosas desde una amplia perspectiva será difícil que llegues a ser un experto en la estrategia.",
    "Si el enemigo piensa en la montaña, imponle el mar; y si él piensa en el mar, imponle la montaña. Éste es el Camino de la estrategia. Esto es propio para que lo investigues cuidadosamente.",
    "Cuando estáis combatiendo contra los enemigos, si tenéis la sensación de estar estancados y de no hacer ningún progreso, abandonad vuestro estado de ánimo y pensad en vuestro corazón que estáis empezando algo nuevo.",
    "Esto es algo imperativo para los guerreros; ignorar la maestría de las armas y la comprensión de las ventajas específicas de cada una de ellas sería indicar una falta de cultura de un miembro de una casa guerrera.",
    "Cuando intentáis alguna táctica sobre un adversario, si no funciona la primera vez, no obtendréis ningún beneficio precipitándoos a hacerla de nuevo. Cambiad vuestras tácticas de manera abrupta, haciendo algo completamente diferente. Si todavía esto no funciona, intentad alguna otra cosa.",
    "En la ciencia militar a gran escala, cuando no podéis discernir el estado del enemigo, fingís lanzar un ataque poderoso para ver cómo reacciona. Habiendo visto los métodos del enemigo, es fácil alcanzar la victoria aprovechándose de diferentes tácticas adaptadas especialmente a cada caso.",
    "En el combate individual, muéstrate primero relajado, y después entra de repente a la carga con fuerza; cuando la mente del contrincante cambie de táctica, es esencial que sigas atentamente lo que hace, no dándole respiro un solo momento, percibiendo la ventaja del momento y juzgando exactamente entonces como ganar.",
    "El budismo es una vía para ayudar a la gente; el confucianismo es una vía para reformar la cultura. Para el médico, curar es una forma de vida; un poeta enseña el arte de la poesía. (...) Las personas practican las vías a las que se sienten inclinadas y desarrollan sus preferencias individuales.",
    "En el arte individual de la guerra, también sucede que un adversario pierda el ritmo en el combate y empiece a derrumbarse. Si no aprovechar esta oportunidad, el adversario se recobrará y empezará a presentarte dificultades. Es esencial seguir con atención cualquier pérdida de posición por parte de tu contrincante, para impedirle que se recupere."
];

const ensenanzasSecretasFrases = [
    `A partir de aquella suposición de los primeros teólogos de que el hombre había sido creado a imagen de Dios, las mentes iniciadas de otros tiempos erigieron la magnífica estructura de la teología sobre la base del cuerpo humano. El mundo religioso de la actualidad ignora casi por completo que la ciencia de la biología constituye el origen de sus doctrinas y sus principios. Muchos de los códigos y las leyes que los teólogos actuales creen que han sido revelaciones directas de la divinidad en realidad son fruto de siglos de ahondar pacientemente en las complejidades de la constitución humana y en las maravillas infinitas reveladas por semejante estudio.`,
    "«La personalidad está colgada de un hilo de la naturaleza del Ser», declara la obra secreta. El hombre es, en esencia, un principio permanente e inmortal y solo su cuerpo atraviesa el ciclo del nacimiento y la muerte. Lo inmortal es la realidad; lo mortal es la irrealidad. Durante cada período de la vida terrenal, la realidad vive en la irrealidad y se libera de ella temporalmente mediante la muerte y permanentemente mediante la iluminación.",
    "Los antiguos no creían que, gracias a la espiritualidad, los hombres se volvieran honrados o racionales, sino, más bien, que la honradez y la racionalidad los volvían espirituales.",
    "Pensar bien, sentir bien y obrar bien son las tres puertas que atraviesa el poder de Cristo al ingresar en el mundo material, donde trabaja para erigir el templo de la hermandad universal. La ignorancia, la superstición y el temor son tres rufianes, por medio de los cuales es asesinado el espíritu del bien y se establece en su lugar un reino falso, controlado por los malos pensamientos, los malos sentimientos y las malas acciones. En el universo material, el mal siempre parece victorioso. «En este sentido -escribe Daniel Sickels-, el mito de los tirios se repite permanentemente en la historia de los asuntos humanos. Orfeo fue asesinado y su cuerpo fue arrojado al Hebro; a Sócrates lo obligaron a beber cicuta, y en todas las épocas hemos visto que el Mal triunfa momentáneamente y la Virtud y la Verdad son calumniadas, perseguidas, crucificadas y asesinadas. Sin embargo, la Justicia Eterna pasa con seguridad y rapidez por el mundo: los tifones, los hijos de la oscuridad, los que conspiran para cometer delitos y todas las formas infinitamente variadas del mal caen en el olvido y la Verdad y la Virtud postradas durante un tiempo surgen envueltas en una majestad más divina y coronadas de gloria eterna.» (Véase The General Ahiman Rezon and Freemason's Guide.)",
    "Platón afirmaba que la música que ennoblecía la mente era mucho más elevada que la que se limitaba a apelar a los sentidos e insistía con firmeza en que la Asamblea Legislativa tenía la obligación primordial de reprimir cualquier música que tuviera un carácter afeminado y lascivo y de fomentar solo la que fuera pura y digna, y también en que las melodías atrevidas y enardecedoras eran para los 296 hombres y las suaves y tranquilizadoras, para las mujeres, con lo cual resulta evidente que la música desempeñaba un papel importante en la educación de la juventud griega.",
    "El desarrollo de la naturaleza espiritual del hombre es una ciencia tan exacta como la astronomía, la medicina o la jurisprudencia. Las religiones se establecieron fundamentalmente para alcanzar este objetivo y de la religión han surgido la ciencia, la filosofía y la lógica como métodos mediante los cuales se puede alcanzar este propósito divino.",
    "Es posible que el mundo moderno conozca un millón de secretos, pero el mundo antiguo conocía uno solo y aquel era mayor que estos millones, que engendran muerte, desastre, tristeza, egoísmo, lujuria y avaricia, mientras que aquel único confiere vida, luz y verdad.",
    "Paracelso: «Hay un sol terrenal, que es la causa de todo el calor, y todos los que son capaces de ver pueden ver el sol y los que son ciegos y no pueden verlo sienten su calor. Hay un sol eterno, que es la fuente de toda la sabiduría y los que tienen los sentidos espirituales despiertos a la vida verán este sol y serán conscientes de su existencia, pero aquellos que no han alcanzado la conciencia espiritual también pueden percibir su poder mediante una facultad interna, llamada intuición».",
    "Con respecto a estas semillas de oro espiritual, tiene importancia el siguiente axioma rosacruz: «Toda semilla es inútil e impotente, a menos que se siembre en la matriz adecuada». Franz Hartmann comenta este axioma con las siguientes palabras esclarecedoras: «El alma no puede desarrollarse ni avanzar sin un cuerpo adecuado, porque es el cuerpo físico lo que le proporciona el material para su evolución». (Véase In the Pronaos of the Temple of Wisdom.)",
    "La investigación ha demostrado no solo que los constructores de tales ciudades y monumentos y los escultores que cincelaron los rostros inescrutables de los dioses eran maestros en su oficio, sino también que en el mundo actual no hay nadie equiparable a ellos. El profundo conocimiento de la matemática y la astronomía que se manifiesta en la arquitectura antigua y el conocimiento igual de profundo de la anatomía que revela la estatuaria griega demuestran que, en ambos casos, sus artífices eran mentes superiores y profundamente ilustradas en el saber que constituía los arcanos de los Misterios.",
    "Pitágoras no era extremista: enseñaba la moderación en todo, más que el exceso en algo, porque creía que un exceso de virtud era, en sí mismo, un defecto. Una de sus frases favoritas era: «Debemos poner todo nuestro empeño en evitar y amputar, a fuego y a espada y por cualquier otro medio, del cuerpo la enfermedad, del alma la ignorancia, del vientre la lujuria, de una ciudad la sedición, de una familia la discordia y de todas las cosas el exceso».",
    "Declaraba que en la naturaleza había amistad de todos para con todos: de los dioses hacia los hombres; de las doctrinas entre sí; del alma con respecto al cuerpo; de la parte racional con la irracional; de la filosofía con respecto a su teoría; de los hombres entre sí; entre compatriotas; que la amistad también existía entre extraños, entre un hombre y su mujer, sus hijos y sus criados. Todos los vínculos en los que no hubiera amistad eran grilletes y no había virtud alguna en mantenerlos. Pitágoras creía que las relaciones eran fundamentalmente mentales, más que físicas, y que un desconocido con un intelecto comprensivo estaba más cerca de él que un consanguíneo cuyos puntos de vista discreparan de los suyos.",
    "En el mundo superior vivían los inmortales y también los arquetipos o los sellos, cuya naturaleza no participaba en modo alguno del material de lo terreno, sino que, como proyectaban sus sombras sobre lo profundo (el mundo inferior), sólo se podían conocer a través de ellas. En el tercero, o mundo inferior, vivían las criaturas que eran partícipes de la sustancia material o participaban en el trabajo con la sustancia material y en ella. Por consiguiente, esta esfera era 235 la morada de los dioses mortales, los demiurgos, los ángeles que trabajan con los hombres, también de los demonios que participan de la naturaleza de la tierra y, por último, de la humanidad y los reinos inferiores, los que transitoriamente pertenecen a la tierra pero son capaces de elevarse por encima de aquella esfera mediante la razón y la filosofía.",
    "Los griegos creían que el mundo [el universo material] estaba compuesto por cuatro elementos -tierra, aire, fuego y agua- y para la mente griega era inevitable la conclusión de que las formas de las partículas de los elementos eran las de los sólidos regulares. Las partículas de tierra eran cúbicas, porque el cubo era el sólido regular que poseía más estabilidad. Las partículas de fuego eran tetraédricas, porque el tetraedro era el sólido más sencillo y, por lo tanto, el más ligero. Las partículas de agua eran icosaédricas, precisamente por el motivo contrario, mientras que las partículas de aire, como intermedias entre las dos últimas, eran octaédricas. El dodecaedro era, para aquellos matemáticos antiguos, el sólido más misterioso; era, con diferencia, el más difícil de construir, porque dibujar con precisión un pentágono regular requería una aplicación bastante compleja del gran teorema de Pitágoras. De ahí la conclusión, como dijo Platón, de que «la divinidad lo utilizó (al dodecaedro regular) para dibujar el plano del universo». (H. Stanley Redgrove en Bygone Beliefs.)",
    "El hecho de que el conocimiento adquirido en los templos le permitiera hacer afirmaciones que tardaron dos mil años en poder ser demostradas prueba por qué Platón y Aristóteles estimaban tanto la profundidad de los Misterios antiguos. En medio de una relativa ignorancia científica y sin la ayuda de ningún instrumento moderno, los sacerdotes-filósofos habían descubierto los verdaderos fundamentos de la dinámica universal.",
    "Para los pitagóricos, la aritmética era la madre de las ciencias matemáticas, como lo demuestra el hecho de que la geometría, la música y la astronomía dependan de ella, a pesar de que ella no dependa de estas tres. Por consiguiente, aunque desaparezca la geometría, la aritmética quedará; en cambio, si se suprime la aritmética, la geometría se elimina. Del mismo modo, la música depende de la aritmética, pero la eliminación de la música solo afecta a la aritmética en cuanto a que limita una de sus manifestaciones.",
    "Era habitual que los filósofos ocultaran el elemento tierra bajo el símbolo de un dragón y a muchos de los héroes de la Antigüedad los enviaban a matar al dragón, para que introdujeran su espada (la mónada) en el cuerpo del dragón (la tétrada), con lo cual se formaba la péntada, el símbolo de la victoria de la naturaleza espiritual sobre la material. Los cuatro elementos se simbolizaban en las primeras escrituras bíblicas como los cuatro ríos que salían del jardín del Edén. Los propios elementos están sometidos al control de los complejos querubines de Ezequiel.",
    "El mago negro no puede usar los símbolos de la magia blanca sin atraer sobre sí las fuerzas de la magia blanca, lo cual resultaría fatal para sus planes, de modo que tiene que distorsionar los hierogramas para que tipifiquen el hecho oculto de que él mismo está distorsionando los principios que los símbolos representan. La magia negra no es un arte fundamental, sino el uso incorrecto de un arte. Por consiguiente, no tiene símbolos propios, sino que se limita a tomar las figuras emblemáticas de la magia blanca y, al invertirlas y darles vuelta, se entiende que es siniestra.",
    "Mediante el pentáculo que hay dentro de su propia alma, el hombre no solo puede dominar y gobernar a todas las criaturas inferiores a sí mismo, sino que puede pedir la consideración de las que son superiores a él.",
    "En su Ten Great Religions, James Freeman Clarke describe como sigue las creencias de los druidas: «Los druidas creían en tres mundos y en la transmigración de uno a otro: un mundo superior a este, en el cual reinaba la felicidad; un mundo inferior, de desdicha, y el estado actual. Esta transmigración servía para castigar y recompensar y también para purificar el alma. En el mundo presente -decían-, el Bien y el Mal están tan bien equilibrados que el hombre tiene la máxima libertad y puede elegir o rechazar ambos.",
    "Un aspecto curioso del mito del dios que muere es el del ahorcado. El ejemplo más importante de esta concepción peculiar se encuentra en los rituales odínicos, en los que Odín se cuelga durante nueve noches de las ramas del árbol del mundo y, además, atraviesa su propio costado con la lanza sagrada. Como consecuencia de aquel gran sacrificio, Odín, mientras estaba suspendido sobre las profundidades de Niflheim, descubrió gracias a la meditación las runas o los alfabetos por medio de los cuales se preservaron después los documentos de su pueblo. Debido a aquella experiencia excepcional, a veces Odín aparece sentado sobre una horca y se ha convertido en el patrono de todos los que han muerto colgados. Desde el punto de vista esotérico, el ahorcado es el espíritu humano que está suspendido del cielo por un solo hilo. La sabiduría, en lugar de la muerte, es la recompensa por aquel sacrificio voluntario durante el cual el alma humana, suspendida sobre el mundo de la ilusión y meditando sobre su irrealidad, recibe la recompensa de alcanzar la autorrealización. Después de considerar todos estos rituales antiguos y secretos, resulta evidente que el misterio del dios que muere era universal entre los colegios iluminados y venerados de las enseñanzas sagradas.",
    "C. M. Gayley, en The Classic Myths, afirma lo siguiente: «Una característica agradable del paganismo antiguo era que le gustaba buscar en cada acción de la naturaleza la mano de la divinidad. La imaginación de los griegos poblaba las regiones de la tierra y el mar de divinidades, a cuya intervención atribuía los fenómenos que nuestra filosofía atribuye a la ley natural».",
    "Según Paracelso, los íncubos y los súcubos (que son masculinos y femeninos, respectivamente) son criaturas parásitas que subsisten en los pensamientos y las emociones negativos del cuerpo astral. Estos términos se aplican también a los organismos superfísicos de los hechiceros y los magos negros. Si bien estas larvae no tienen nada de seres imaginarios, son, a pesar de todo, fruto de la imaginación. Para los sabios antiguos eran la causa invisible del vicio, porque rondan en los éteres que rodean a las personas débiles moralmente y sin cesar las incitan a cometer excesos degradantes. Por este motivo, frecuentan el ambiente de antros, tugurios y burdeles, donde se aferran a los desventurados que se han entregado a la iniquidad. Al dejar que sus sentidos se insensibilicen como consecuencia del abuso de drogas que crean dependencia o de estimulantes alcohólicos, el individuo se pone en contacto temporalmente con estos habitantes del plano astral.",
    "En su De Ente Spirituali, Paracelso escribe lo siguiente acerca de estos seres malignos: «Ninguna persona sana y pura puede obsesionarse con ellos, porque tales larvae solo pueden afectar a los seres humanos si estos les hacen sitio en su mente. Una mente sana es un castillo que no se puede invadir si su amo no lo quiere; pero si se les permite entrar, despiertan las pasiones de hombres y mujeres, crean ansias en ellos, provocan malos pensamientos que causan perjuicios en el cerebro; agudizan el intelecto animal y ahogan el sentido moral. Los espíritus del mal solo obsesionan a aquellos seres humanos en los que predomina la animalidad. No se pueden poseer las mentes que están iluminadas por el espíritu de la verdad; solo se pueden someter a su influencia aquellas que habitualmente se rigen por sus propios impulsos inferiores». (Véase Paracelsus, de Franz Hartmann.)",
    "Los obstáculos con los que se enfrenta actualmente la investigación científica se deben, en gran medida, a las limitaciones sesgadas impuestas por quienes no están dispuestos a aceptar nada que trascienda de las percepciones concretas de los cinco sentidos humanos principales.",
    "Los mejores de nuestros médicos populares son los que causan menos daño. Sin embargo, lamentablemente, algunos envenenan a sus pacientes con mercurio y otros los purgan o hacen que mueran desangrados. Algunos han aprendido tanto que su saber les ha hecho perder todo el sentido común, mientras que otros se preocupan mucho más de su propio provecho que de la salud de sus pacientes. Una enfermedad no cambia de estado para ajustarse a los conocimientos del médico, sino que el médico debería comprender las causas de la enfermedad. El médico debería estar al servicio de la naturaleza, en lugar de ser su enemigo; debe ser capaz de guiarla y dirigirla en su lucha por la vida, en lugar de ponerle, por su intromisión poco razonable, nuevos obstáculos en el camino de la recuperación». (Del Paragranum, traducido por Franz Hartmann.)",
    "Los llamados «nuevos descubrimientos» de la ciencia moderna a menudo no son más que redescubrimientos de secretos bien conocidos por los sacerdotes y los filósofos del paganismo antiguo. Como consecuencia de la crueldad del hombre para con el hombre se han perdido registros y fórmulas que, de haberse preservado, habrían resuelto muchos de los problemas principales de esta civilización.",
    "En un manuscrito primitivo inédito, un filósofo anónimo declara que la alquimia, el cabalismo, la astrología y la magia habían sido en un principio ciencias divinas, pero que se habían pervertido hasta convertirse en doctrinas falsas, que alejaban aún más de su objetivo a los que buscaban la sabiduría.",
    "A continuación, el autor anónimo afirma lo siguiente: Por filosofía se ha de entender el conocimiento del funcionamiento de la naturaleza, mediante el cual el hombre aprende a escalar las montañas más altas, por encima de las limitaciones de los sentidos. Entiéndase por cabalismo el lenguaje de los seres angelicales o celestiales y quien lo domine podrá conversar con los mensajeros de Dios. En la montaña más alta está la Escuela de Magia (la Magia Divina, que es el lenguaje de Dios), en la cual el propio Dios enseña al hombre la verdadera naturaleza de todas las cosas.",
    "¿Es posible transmutar los metales de baja ley en oro o se trata de una idea que bien puede despertar las burlas de los eruditos del mundo moderno? La alquimia fue más que un arte especulativo: fue también un arte activo. Desde la época del Hermes inmortal, los alquimistas han afirmado -y no les faltaban pruebas para corroborarlo– que podían fabricar oro a partir de estaño, plata, plomo y mercurio. Resulta insostenible que la pléyade de mentes filosóficas y científicas brillantes que, durante un período de dos mil años, afirmaron que era posible la transmutación y la multiplicación de los metales fueran totalmente sensatos y racionales en todos los demás problemas filosóficos y científicos y que, no obstante, estuvieran equivocados sin remedio en este único punto.",
    "Muchos grandes alquimistas y filósofos herméticos ocupan un lugar de honor en la galería de personajes famosos, mientras que sus innumerables críticos permanecen en el anonimato.",
    "Albert Pike se pone de parte del filósofo alquímico cuando afirma que el oro de los herméticos era una realidad. Dice lo siguiente: «La ciencia hermética, como todas las ciencias reales, es demostrable matemáticamente. Sus resultados, aunque sean materiales, son tan rigurosos como los de una ecuación correcta. El oro hermético no es solo un dogma auténtico, una luz sin sombra, una verdad que no está empañada por la falsedad, sino también un oro material, real, puro, el metal más precioso que se puede encontrar en las minas de la tierra».",
    "...una obra que, supuestamente, narra su búsqueda de la piedra filosofal, aparece una afirmación muy significativa: «Estudiad lo que sois, a lo que pertenecéis, lo que conocéis de lo que sois, porque esto es en verdad lo que sois. Lo que hay fuera de vos está también en vuestro interior, así escribió Trismosin».",
    "Ponte a trabajar, como he hecho yo antes que tú, teme a Dios, ama a tu prójimo desde el fondo de tu alma y sinceramente. Dedícate por tu cuenta a la operación manual y, cuando te pongas a trabajar en ella, muchos de los hermanos de nuestra santa orden se manifestarán ante ti, en privado. En cuanto a mí, gracias al Dios eterno, he escrito la verdad que he descubierto mediante la oración y la búsqueda en la naturaleza, una obra que he visto con mis propios ojos y que he extraído con mis manos. Por lo tanto, suscribo este testamento con mi sangre, el último día de mi vida, en mi lecho de muerte. Actum Leyden, a 27 de marzo de 1662.",
    "La filosofía otorga vida, porque revela la dignidad y el propósito de la vida. El materialismo otorga muerte, porque embota o nubla las facultades del alma humana que deberían responder a los impulsos vivificantes del pensamiento creativo de la virtud enaltecedora. ¡Cuán por debajo de estos principios están las leyes por las que nos regimos los hombres en el siglo xx! Hoy el hombre, una criatura sublime con una capacidad infinita de autosuperación, en su esfuerzo por ser fiel a principios falsos, se aparta de su derecho inalienable al conocimiento sin darse cuenta de las consecuencias- y cae en la vorágine de la ilusión material. Dedica el período precioso de sus años terrenales al esfuerzo penosamente inútil de establecerse como un poder imperecedero en un reino de cosas perecederas. Poco a poco va desapareciendo de su mente objetiva el recuerdo de su vida como ser espiritual y concentra todas sus facultades parcialmente despiertas en el hervidero de la colmena de la laboriosidad, que, en un momento dado, llega a ser para él la única realidad. Desde las elevadas alturas de su egoísmo, se hunde poco a poco en las sombrías profundidades de la fugacidad. Cae al nivel de las bestias y de forma animal masculla los problemas que surgen de su conocimiento insuficiente del plan divino. Aquí, en la confusión chillona 749 de un gran infierno industrial, político y comercial, los hombres se retuercen en medio del dolor que se provocan ellos mismos y, tendiendo las manos hacia las nieblas que se arremolinan, tratan de agarrar y de sujetar los fantasmas grotescos del éxito y el poder.",
    "Hasta la filosofía se ha convertido en un cúmulo prosaico y heterogéneo de nociones contradictorias.",
    "Desconocedor de la causa de la vida, desconocedor de la finalidad de la vida y desconocedor de lo que hay más allá del misterio de la muerte, aunque posee en su interior la respuesta a todas estas preguntas, el hombre está dispuesto a sacrificar lo hermoso, lo verdadero y lo bueno que hay dentro y fuera de sí mismo sobre el altar sangriento de la ambición mundana. El mundo de la filosofía -aquel jardín hermoso del pensamiento en el cual viven los sabios, unidos por el vínculo de la fraternidad- desaparece de la vista y en su lugar surge un imperio de piedra, acero, humo y odio, un mundo en el cual millones de criaturas potencialmente humanas corretean de aquí para allá en un esfuerzo desesperado por existir y, al mismo tiempo, mantener la inmensa institución que han levantado y que, como un poderoso gigante, retumba inevitablemente hacia un fin desconocido.",
    "En este imperio material que el hombre erige con la vana creencia de que puede eclipsar el reino de los celestiales, todo se convierte en piedra. Fascinado por el oropel del triunfo, el hombre contempla fijamente el rostro de la codicia, que, cual Medusa, lo deja petrificado.",
    "En este período comercial, lo único que interesa a la ciencia es clasificar el conocimiento físico e investigar las partes temporales e ilusorias de la naturaleza. Los descubrimientos que considera prácticos se limitan a sujetar más estrechamente al hombre con los lazos de la limitación física. Hasta la religión se ha vuelto materialista: la belleza y la dignidad de la fe se miden mediante pilas inmensas de mampostería, la cantidad de propiedades inmobiliarias o el balance financiero.",
    "La única esperanza del mundo es la filosofía, porque todas las penas de la vida moderna se deben a la falta de un código filosófico adecuado. Los que perciben al menos en parte la dignidad de la vida no pueden por menos que darse cuenta de la superficialidad aparente en las actividades de esta época. Bien se ha dicho que nadie triunfará mientras no desarrolle su filosofía de vida.",
    "Tampoco alcanzará la verdadera grandeza ninguna raza ni ninguna nación, mientras no formule una filosofía adecuada ni dedique su existencia a una política coherente con ella. Durante la guerra mundial, cuando la llamada civilización arrojó la mitad de sí misma contra la otra mitad en un arrebato de odio, los hombres destruyeron sin piedad algo más precioso incluso que la vida humana: borraron los recuerdos del pensamiento humano que pueden dirigir la vida con inteligencia. En verdad declaró Mahoma que la tinta de los filósofos era más preciosa que la sangre de los mártires.",
    "Durante la guerra mundial, cuando la llamada civilización arrojó la mitad de sí misma contra la otra mitad en un arrebato de odio, los hombres destruyeron sin piedad algo más precioso incluso que la vida humana: borraron los recuerdos del pensamiento humano que pueden dirigir la vida con inteligencia. En verdad declaró Mahoma que la tinta de los filósofos era más preciosa que la sangre de los mártires. Documentos inestimables, constancias de logros inapreciables, conocimientos basados en siglos de observación y experimentación pacientes por los elegidos de la tierra: todos fueron destruidos, casi sin el menor reparo. ¿Qué era el conocimiento, qué eran la verdad, la belleza, el amor, el idealismo, la filosofía o la religión, en comparación con el deseo del hombre de controlar un punto infinitesimal en los campos del cosmos durante un fragmento de tiempo inestimablemente diminuto?",
    "El microscopio revela al hombre su significancia y el telescopio, su insignificancia. Por medio de las eternidades de la existencia, el hombre va aumentando poco a poco tanto su sabiduría como su comprensión; su conciencia creciente va incluyendo más de lo externo dentro de la zona del ser. Incluso en su estado actual de imperfección, el hombre se va dando cuenta de que nunca puede ser verdaderamente feliz mientras no sea perfecto y que de todas las facultades que contribuyen a su autoperfección ninguna iguala en importancia al intelecto racnal.",
    "Quien no conoce más vida que la física solo es ignorante, pero quien declara que la vida física es lo más importante y la eleva al puesto de la realidad suprema es ignorante de su propia ignorancia.",
    "Siguiendo el camino que señalan los sabios, quien busca la verdad llega finalmente a la cima del monte de la sabiduría y, al mirar hacia abajo, contempla el panorama de la vida que se extiende ante él. Las ciudades de las planicies no son más que motitas y por todas partes el horizonte queda oculto tras la bruma gris de lo Desconocido. Entonces el alma se da cuenta de que la sabiduría reside en la amplitud de miras y se incrementa en función de la perspectiva. Entonces, como los pensamientos del hombre lo elevan hacia el cielo, las calles se pierden en ciudades, las ciudades en naciones, las naciones en continentes, los continentes en la tierra, la tierra en el espacio y el espacio en la eternidad infinita, hasta que al final solo quedan dos cosas: el Yo y la bondad de Dios.",
    "Los filósofos no nacen ni mueren, porque, cuando llegan a darse cuenta de la inmortalidad, son inmortales. Cuando han alcanzado la comunión con el Yo, se dan cuenta de que en su interior hay un fundamento inmortal que no desaparece. Sobre una base viva y vibrante -el Yo- erigen una civilización que perdurará después de que el sol, la luna y las estrellas hayan dejado de existir. El tonto no vive más que para el presente; el filósofo vive para siempre.",
    "El hombre puede vivir dos vidas. Una es una lucha desde el vientre hasta la tumba, cuya duración se mide por algo que el propio hombre ha creado: el 757 tiempo. Bien podemos llamarla «la vida inconsciente». La otra vida va desde el entendimiento hasta el infinito. Comienza con la comprensión, dura para siempre y se consuma en el plano de la eternidad. Se la llama «la vida filosófica»."
];

const unabomberFrases = [
    "El sistema no existe y no puede existir para satisfacer las necesidades humanas. En vez, es el comportamiento humano el que tiene que ser modificado para encajar en las necesidades del sistema. Esto no tiene nada que ver con la ideología política o social que pueda pretender guiar el sistema tecnológico. Es culpa de la tecnología, porque el sistema no está guiado por la ideología sino por las necesidades técnicas.",
    "«Hoy en día, en las regiones tecnológicamente avanzadas, el hombre lleva vidas muy similares a pesar de las diferencias geográficas, religiosas o políticas. Las vidas diarias de un oficinista cristiano de un banco en Chicago, un oficinista budista en un banco de Tokio, y uno comunista en Moscú son mucho más parecidas que la vida de cualquiera de ellos con un hombre que viviera hace mil años. Los parecidos son el resultado de una tecnología común...» L. Sprague de Camp, The Ancien Engineers, ediciones Ballantine, página 17.",
    "Las vidas de los tres oficinistas de banco no son IDÉNTICAS. La ideología tiene ALGÚN efecto. Pero todas las sociedades tecnológicas, a fin de sobrevivir, tienen que evolucionar APROXIMADAMENTE a lo largo de la misma trayectoria. Por supuesto el sistema satisface muchas necesidades humanas, pero hablando en general, hace esto sólo en la medida en que le beneficia el hacerlo. Son las necesidades del sistema.las que son supremas, no las de los seres humanos. Por ejemplo, el sistema provee a la gente con comida porque no puede funcionar si todo el mundo está muerto de hambre; atenta contra las necesidades psicológicas de la gente siempre que pueda ser CONVENIENTE el hacerlo, porque no puede funcionar si demasiada gente se vuelve depresiva o rebelde. Pero el sistema por buenas razones, sólidas y prácticas, tiene que ejercer presión constante sobre la gente para moldear su comportamiento hacia sus necesidades.",
    "¿Demasiada basura acumulada? El gobierno, los medios, el sistema educacional, los medioambientalistas, todo el mundo nos inunda con masas de propaganda sobre el reciclado. ¿Necesita más personal técnico? Un coro de voces exhorta a los chavales a que estudien ciencias. Nadie se para a preguntar si es inhumano el forzar a los adolescentes a consumir el grueso de su tiempo estudiando materias que la mayoría odian.",
    "Imagina un alcohólico sentado con un tonel de vino en frente. Supón que empieza a decirse, «el vino no es malo si se usa con moderación, porque pequeñas cantidades son incluso buenas...» Bueno ya sabes lo que va a pasar. No olvides nunca que la raza humana es simplemente como un alcohólico con un tonel de vino.",
    "El concepto de «salud mental» en nuestra sociedad está largamente definido por el alcance del comportamiento de una persona esté de acuerdo con las necesida-des del sistema y que lo haga sin mostrar signos de tensión.",
    "Incluso si el progreso médico se pudiera mantener sin el resto del sistema tecnológico, traería en sí ciertos males. Supongamos por ejemplo que se descubriera una cura para la diabetes. La gente con una tendencia genética a la diabetes serían capaces de sobrevivir y reproducirse tan bien como cualquier otro. La selección natural contra los genes de la diabetes pararía y se dispersarían por la población. (Esto puede estar ocurriendo ya a cierta extensión, desde que la diabetes, si bien no es curable, puede ser controlada mediante el uso de insulina). Lo mismo ocurrirá con muchas otras enfermedades, a cuya sensibilidad es afectada por la degradación genética de la población. La única solución sería alguna clase de programa de *eugenesia o de ingeniería genética extensiva de seres humanos, por lo que el hombre en el futuro no sería por más tiempo una creación de la naturaleza, o de la casualidad, o de dios (dependiendo de tus opiniones religiosas o filosóficas), sino un producto manufacturado.",
    "Imagina una sociedad que somete a la gente a condiciones que los hacen terriblemente infelices, entonces les da drogas para quitarle su infelicidad. ¿Ciencia ficción? Ya está ocurriendo en cierta extensión en nuestra sociedad. Es bien sabido que la tasa de depresiones clínicas se ha incrementado enormemente en las décadas recientes. Creemos.que esto es debido al colapso del proceso de poder, como explicamos en los párrafos 59-76. Pero incluso si estamos equivocados, el incremento de la tasa de depresiones es ciertamente el resultado de ALGUNAS condiciones que existen en la sociedad de hoy. En vez de extirpar las condiciones que hacen que la gente esté deprimida, las sociedad moderna les da drogas antidepresivas. En realidad, los antidepresivos son un medio de modificar el estado interno de un individuo de tal manera que le permita tolerar las condiciones sociales que de otra manera encontraría intolerables. (Sí, sabemos que la depresión es con frecuencia de origen puramente genético.",
    "Supongamos que se descubre un rasgo biológico que incrementa la probabilidad de que un niño crezca para ser un criminal, y supongamos alguna clase de terapia genética que pueda extirpar ese rasgo. Por supuesto, la mayoría de los padres cuyos hijos posean el rasgo lo someterían a la terapia. Sería inhumano el hacerlo de otra manera, puesto que el niño probablemente tendría una vida miserable si creciera para ser un criminal. Pero muchas o la mayoría de las sociedades primitivas tienen una tasa baja de crímenes en comparación con la nuestra, aunque no tuvieran ni métodos de alta tecnología para criar a los niños, ni sistemas crueles de castigo. Ya que no hay razón para suponer que más hombres modernos que primitivos han iniciado tendencias depredadoras, la alta tasa de crímenes en nuestra sociedad tiene que ser debida a las presiones que las condiciones modernas ponen en la gente, a las cuales muchos no pueden o no podrán ajustarse. Así, un tratamiento diseñado para extirpar tendencias criminales potenciales es, al menos en parte, una manera de rediseñar a la gente para que ajusten a los requerimientos del sistema.",
    "Uno tiene que contrapesar el luchar y morir contra la pérdida de la libertad y la dignidad. Para muchos de nosotros, la libertad y la dignidad son más importantes que una vida larga o el evitar el sufrimiento físico. Además, todos tenemos que morir alguna vez y puede ser mejor morir luchando para sobrevivir, o por una causa, que vivir una vida larga pero vacía y carente de sentido.",
    "Algunos izquierdistas podría parecer que se oponen a la tecnología, pero sólo se opondrán mientras sean intrusos y el sistema tecnológico esté controlado por no izquierdistas. Si alguna vez el izquierdismo dominase la sociedad, por lo que el sistema tecnológico se convirtiera en una herramienta es sus manos, lo usarían entusiastamente y promocionarían su crecimiento. Haciendo esto estarían repitiendo el patrón que el izquierdismo ha enseñado una y otra vez en el pasado. Cuando en Rusia los bolcheviques eran intrusos, se oponían vigorosamente a la censura y a la policía secreta, defendían la autodeterminación de las minorías étnicas, etc; pero tan pronto como tomaron el poder, impusieron una censura implacable y crearon una policía secreta más dura que ninguna de las que existiera bajo los zares y oprimieron a las minorías étnicas al menos tanto como lo hicieron estos. En los Estados Unidos, hace un par de décadas cuando eran una minoría en nuestras universidades, los profesores izquierdistas eran los que proponían vigorosamente la libertad académica, pero hoy, en aquellas universidades donde han pasado a ser mayoría, se han visto preparados para quitar al resto la libertad académica. (Esto es «corrección política»). Lo mismo ocurrirá con los izquierdistas y la tecnología: la utilizarán para oprimir a los demás si alguna vez cae bajo su propio control.",
    "Diversos pensadores han señalado que el izquierdismo es un tipo de religión. No lo es en el estricto sentido de la palabra porque esta doctrina no postula la existencia de ningún ser supranatural. Pero para los izquierdistas, su doctrina juega el mismo papel psicológico que para mucha gente la religión. NECESITAN creer en el izquierdismo, juega un papel vital el su economía psicológica. Sus creencias no son fácilmente modificables por la lógica o por los hechos. Tienen una profunda convicción de que es moralmente Correcto con una C mayúscula y que no sólo tiene el derecho sino el deber de imponer su moral a todo el mundo.",
    "Los seres humanos tienen una necesidad (probablemente basada en la biología) por algo que llamaremos el «proceso de poder». Esto está estrechamente relacionado a la necesidad de poder (la cual está ampliamente reconocida) pero no es exactamente la misma cosa. El proceso de poder tiene cuatro elementos. Los tres más claramente delineados los llamamos finalidad, esfuerzo y logro de la finalidad. (Todo el mundo necesita tener finalidades cuyo logro requiera esfuerzo, y necesita triunfar logrando al menos alguna de sus finalidades).",
    "Pero no todo aristócrata ocioso se convertía en aburrido y desmoralizado. Por ejemplo, el emperador Hirohito, en vez de hundirse en un hedonismo decadente, se volvió un apasionado de la biología marina, un campo en el que se distinguió. Cuando la gente no tiene que esforzarse en satisfacer sus necesidades físicas a menudo crean finalidades artificiales para ellos mismos. En muchos casos persiguen estas finalidades con la misma energía y compromiso emocional que hubieran puesto de otro modo en buscar sus necesidades físicas. Así, los aristócratas del Imperio Romano tenían sus pretensiones literarias, muchos aristócratas europeos hace pocos siglos invertían mucho tiempo y energía en cazar, siendo que no necesitaban la carne, otros aristócratas rivalizaban por la posición social a través de elaborados despliegues de riqueza, y unos pocos aristócratas, como Hirohito, han girado hacia la ciencia.",
    "En la sociedad industrial moderna sólo es necesario un mínimo esfuerzo para satisfacer las necesidades físicas propias. Es suficiente el atravesar un programa de entrenamiento para adquirir alguna pequeña escala técnica, después llegar al trabajo puntal y ejercer un esfuerzo muy modesto para mantenerlo. Los únicos requisitos son una cantidad moderada de inteligencia y, la mayor parte de todo, simple OBEDIENCIA.",
    "Hay buenas razones para creer que el hombre primitivo sufría menos tensión y frustración y estaba más satisfecho con su forma de vida de lo que está el hombre moderno.",
    "Entre las condiciones anormales presentes en la sociedad industrial moderna están la excesiva densidad de población, el aislamiento del hombre de la naturaleza, la excesiva rapidez del cambio social y el colapso de las comunidades naturales de pequeña escala tales como la familia prolongada, el pueblo o la tribu..",
    "Para las sociedades primitivas el mundo natural (que normalmente cambiaba sólo despacio) proporcionaba un armazón estable y por eso una sensación de seguridad. En el mundo moderno es la sociedad humana la que domina la naturaleza al contrario que antes, y la sociedad moderna se transforma muy rápidamente debido al cambio tecnológico. Así que no hay un armazón estable.",
    "¡Los conservadores son unos mentecatos! Se quejan de la decadencia de los valores tradicionales y sin embargo soportan con entusiasmo el progreso tecnológico y el crecimiento económico. Aparentemente nunca se les ha ocurrido que no puedes hacer cambios rápidos y drásticos en la tecnología y en la economía de la sociedad sin causar cambios rápidos en todos los otros aspectos de esta, y que esos cambios rápidos inevitablemente rompen los valores tradicionales.",
    
]

function Libro(titulo, autor, fecha, frases, foto){
    this.titulo = titulo
    this.autor = autor
    this.fecha = fecha
    this.frases = frases
    this.foto = foto
};



const libros = [
    new Libro("Meditaciones", "Marco Aurelio", "Circa 170", meditacionesFrases, "https://www.biografiasyvidas.com/biografia/m/fotos/marco_aurelio.jpg"),
    new Libro("El libro de los 5 anillos", "Miyamoto Musashi", "19 de mayo de 1645", cincoAnillosFrases, "https://artelista.s3.amazonaws.com/obras/big/7/9/8107100370944657.jpg"),
    new Libro("Las Enseñanzas Secretas de Todos los Tiempos", "Manly P. Hall", "1928", ensenanzasSecretasFrases, "https://upload.wikimedia.org/wikipedia/commons/0/05/Manly_P._Hall.jpg"),
    new Libro("La Sociedad Industrial y su Futuro", "Theodore Kaczynski (UNABOMBER)", "19 de septiembre de 1995", unabomberFrases, "https://upload.wikimedia.org/wikipedia/commons/3/37/Theodore_Kaczynski.jpg")
];

module.exports.libros=libros;